spring:
  servlet:
    multipart:
      max-file-size: 500MB      # 单个文件允许的最大大小
      max-request-size: 2048MB   # 单次请求允许的最大大小
  application:
    name: backend-user
  datasource:
    url: jdbc:postgresql://${DB_HOST:lasteamcity.ddns.net}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Gp9#q2Wz!mR6*xK4}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 151
      minimum-idle: 5
  jpa:
    hibernate:
      # 开发环境可以用 update，生产环境强烈建议用 validate 并配合 Flyway/Liquibase
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:root@lasteamcity.ddns.net:27017/admin
    redis:
      host: ${REDIS_HOST:lasteamcity.ddns.net}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:las} # 如果没有密码留空
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
springdoc:
  swagger-ui:
    path: /api-docs.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
remote:
  ws:
    url: ws://103.40.14.23:57211
    token: '@LazyAlienServer'
server:
  port: 8081
secret:
  jwt:
    #这里的token-salt用于生成激活链接
    token-salt: "八重神子让我魅力无限，有一次我们班平均分倒数第一，老师气坏了，指着我们破口大骂，你们是我带过的最差的一届！我心想，这么骂下去也不是办法，有什么办法可以控制老师情绪了，有了，我想起了原神中最有魅力的八重神子，于是我模仿着八重的姿态走上了讲台，摸了摸老师的头，怎么啦，小家伙，你看起来不太开心，说完，我舔了舔爪子，学狐狸嗷呜叫了起来，全班同学都震惊到了，这就是八重神子吧？太美了，好妖娆，老师也被我迷住了，表情也变得温和，慈祥，后来，这件事被同学们发到网上爆火了起来，各大导演纷纷找到我，让我去演姐己，说我有狐狸那种邪魅的劲，但我都拒绝了，因为八重神子和妲己不一样，一天下午，我打开了手机，公司老总给我发了这样一条信息，你要是姐己，我愿意当你的纣王，你要是八重，我愿意当你的雷电将军！我感动极了，马上找到了公司老总，嗷呜，我模仿着狐狸的模样，老总看到后心都化了，把我拥入怀里，你是我见过，最美的八重神子… "


    key: 'c(<sJM3RMjpv-RV?6Z&TV]a7SRMe3AKC>ajZTT,WTUyPWJ@+vfYn"Af85-4j!Fa2HV&CSxxR+MX|B@vyAfCJ|2uce.R+s)?2cGA<C&7Q;N]%t<(RS!A:%V2v[G:"W)U-8[k-Wa|s"Uxf,*SfbUQ#NFvY%?Wd5:|man!3U>h2bKXr7>?kT%h?S6D(*]MaPvZ.m]TERR#@6#rp,U@m:2:cHWkxt&rBAHvtE>=Ket&f55Cs(RWTY-_"+A;*[Ge*xYx?'

